### ISSUE TITLE
Head Radius to Improve Rotation Translation Independence

### ISSUE THREAD

**Issue by minimufffin** [opentrack/neuralnet-tracker-traincode#1]
Hey, I have been using neural net tracker on OpenTrack for a few months and I'm very impressed. I was modifying the ftnoir neural net code on OpenTrack for my own personal use to get better depth with my RealSense cameras. The only thing I would like to be improved is head rotation to not affect translation. 

I realize there is a calibration button to do this, but I've had mixed and unreliable results with that. I read in this repo that the NN outputs head radius, so I would like to use that, transform into a 3D radius, and offset the z axis by that amount. So, is there any where in your OpenTrack code that uses the head radius output from your model, can you point me to it? Thank you, your model is fantastic.

**Comment by DaWelter** [comment]
Hi, and thanks.

Yes, the calibration could be better. I had the same experiences with it.

You must be looking for this place https://github.com/opentrack/opentrack/blob/master/tracker-neuralnet/ftnoir_tracker_neuralnet.cpp#L736.

**Comment by minimufffin** [comment]
Thanks! That helps a lot
